### ISSUE TITLE
Error installing the app

### ISSUE THREAD

**Issue by maxbellec** [YunoHost-Apps/restic-s3_ynh#2]
### Describe the bug

When installing the app, I get an error Unable to install restic-s3: An error occurred inside the app installation script

Full install logs : https://paste.yunohost.org/raw/alayahonuy

### Context

- Hardware: VPS
- YunoHost version: 11.2.7
- I have access to my server: SSH + webadmin
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: no
- Using, or trying to install package version/branch: using the git link, main branch

### Steps to reproduce

Use webadmin, install with git link, fill S3 data and click install.

### Expected behavior

App gets installed

### Logs

Full install logs : https://paste.yunohost.org/raw/alayahonuy

**Comment by Tagadda** [comment]
This app is not released yet.
